name: Create Release
on:
  push:
    branches:
      - master

jobs:
 
  ############################################
  # Publish Package
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: |
          cd src
          npm install
          npm ci
          npm publish
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.MPMJS_TOKEN }}